apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  resources:
    requests:
      storage: 10Gi 
  volumeMode: Filesystem
  storageClassName: mysql-data
  accessModes:
    - ReadWriteOnce
